#!/usr/bin/env python3
"""
build-page-images.py — regenerate src/app/page-images.ts.

Lists every image each page actually renders, hero first, so sitemap.ts can
declare them all as <image:image> rather than just the hero. Takes whatever is
inside <main>, which covers both layouts — articles (art-hero, art-inline-img,
art-gallery-grid) and hubs (hub-hero-img, hub-card-img, hub-group-media) —
instead of naming individual containers, which is how the hub's group images
were missed the first time.

Excludes the related-guides module and the image-credits list: those show other
articles' pictures, which belong to those pages' sitemap entries, not this one.

    python3 scripts/build-page-images.py
"""
import re, json, glob, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASE = "https://panamaspot.com"
CAP = 12                    # sitemap image entries per page

def page_images(s):
    main = re.search(r"(?s)<main\b.*?</main>", s)
    body = main.group(0) if main else s
    for pat in (r"(?s)<!--RELATED-MODULE-->.*?<!--/RELATED-MODULE-->",
                r"(?s)<!--IMGCREDITS-->.*?<!--/IMGCREDITS-->",
                r'(?s)<aside class="evb-rail".*?</aside>'):
        body = re.sub(pat, "", body)

    urls, seen, out = [], set(), []
    hero = (re.search(r'art-hero-img-full"><img[^>]*\bsrc="([^"]+)"', s)
            or re.search(r'hub-hero-img"><img[^>]*\bsrc="([^"]+)"', s))
    if hero:
        urls.append(hero.group(1))
    urls += re.findall(r'<img[^>]*\bsrc="([^"]+)"', body)

    for u in urls:
        u = u.replace("&amp;", "&")
        key = re.sub(r"[?&]w=\d+", "", re.sub(r"/\d+px-([^/]+)$", r"/\1", u))
        if key in seen:
            continue
        seen.add(key)
        out.append(u if u.startswith("http") else BASE + u)
    return out[:CAP]

def main():
    pages = {}
    for f in sorted(glob.glob("public/articles/*.html") + glob.glob("public/es/articles/*.html")):
        imgs = page_images(pathlib.Path(f).read_text(encoding="utf-8"))
        if imgs:
            pages["/" + f.replace("public/", "")[:-5]] = imgs

    lines = ["/* Every image each page renders, hero first — generated by",
             "   scripts/build-page-images.py from public/. Used for the",
             "   <image:image> entries in the sitemap so Google Images sees the whole",
             "   set, not just the hero. Do not edit by hand. */",
             "export const pageImages: Record<string, string[]> = {"]
    for k, v in sorted(pages.items()):
        lines.append(f"  {json.dumps(k)}: [")
        lines += [f"    {json.dumps(u)}," for u in v]
        lines.append("  ],")
    lines.append("};\n")
    (ROOT / "src/app/page-images.ts").write_text("\n".join(lines), encoding="utf-8")
    print(f"  {len(pages)} pages, {sum(len(v) for v in pages.values())} images")
    print(f"  bocas hub: {len(pages.get('/articles/bocas-del-toro', []))} images")

if __name__ == "__main__":
    main()
